kind: HyperConverged
apiVersion: hco.kubevirt.io/v1beta1
metadata:
  annotations:
    deployOVS: 'false'
  name: kubevirt-hyperconverged
  namespace: openshift-cnv
spec: 
  workloadUpdateStrategy:
    workloadUpdateMethods: 
    - LiveMigrate 
    - Evict 
    batchEvictionSize: 10 
    batchEvictionInterval: "1m0s" 