apiVersion: v1
kind: Secret
metadata:
  name: secrets-rhdh
stringData:
  # --- Truncated ---

  # TODO: Change auth session secret.
  AUTH_SESSION_SECRET: "my super auth session secret - change me!!!"

   # TODO: Replace Backstage URL

  # Example https://backstage.apps.cluster-wdw6r.wdw6r.gcp.redhatworkshops.io
  BACKSTAGE_URL: "CHANGE"
  # Example *.apps.cluster-wdw6r.wdw6r.gcp.redhatworkshops.io
  HOST_ALLOW: "CHANGE"

  # ARGOCD.
  ARGOCD_USERNAME: "admin"
  # TODO: set ARGOCD password
  # argocd password: oc get secret/openshift-gitops-cluster -n openshift-gitops -o jsonpath='{.data.admin\.password}' | base64 -d
  ARGOCD_PASSWORD: CHANGE
  # TODO: set ARGOCD password
  # get argocd URL: oc get routes openshift-gitops-server -n openshift-gitops -o jsonpath='{.spec.host}'  
  ARGOCD_URL: "CHANGE"

 # TODO: KEYCLOAK
  KEYCLOAK_REALM: "backstage" 
  KEYCLOAK_CLIENTID: "backstage"
  KEYCLOAK_CLIENTSECRET: "my-predefined-client-secret"
  # URL example Replace <rhdh_dns>: https://<rhdh_dns>/realms/backstage
  KEYCLOAK_URL: "CHANGE"
  
  # URL example Replace <rhdh_dns> by keycloak service name: https://<rhdh_dns>:8443 or https://example-keycloak-service.keycloak.svc.cluster.local:8443
  KEYCLOAK_URL_CATALOG: "CHANGE"
  
  # TODO: Replace <rhdh_dns> https://<rhdh_dns>/api/auth/oidc/handler/frame
  KEYCLOAK_CALLBACK_URL: "CHANGE"
 
 
 # TODO: KUBERNETES
  # first you need to create a service account token: oc apply -f infra/developerhub/service-account-token-secret.yaml
  # oc -n rhdh-operator get secret rhdh-sa-token -o go-template='{{.data.token | base64decode}}'
  K8S_SERVICE_ACCOUNT_TOKEN: CHANGE
  
  # URL example https://api.cluster-wdw6r.wdew.gcp.redhatworkshops.io:6443
  K8S_API_URL: "CHANGE"
  
  # GITHUB
  GITHUB_APPID: CHANGE
  GITHUB_CLIENTID: CHANGE
  GITHUB_CLIENTSECRET: CHANGE
  GITHUB_PRIVATEKEY: |
            CHANGE  
type: Opaque




