apiVersion: v1
kind: Secret
metadata:
  name: secrets-rhdh
stringData:
  # --- Truncated ---

  # TODO: Change auth session secret.
  AUTH_SESSION_SECRET: "my super auth session secret - change me!!!"

  # TODO: user pool app client ID
  AWS_COGNITO_APP_CLIENT_ID: "my-aws-cognito-app-client-id"

  # TODO: user pool app client Secret
  AWS_COGNITO_APP_CLIENT_SECRET: "my-aws-cognito-app-client-secret"

  # TODO: Replace region and user pool ID
  AWS_COGNITO_APP_METADATA_URL: "https://cognito-idp.[region].amazonaws.com/[userPoolId]/.well-known/openid-configuration"

  # TODO: Replace <rhdh_dns>
  SERVICE_ACCOUNT_TOKEN: "https://[rhdh_dns]/api/auth/oidc/handler/frame"

  # TODO: Replace Backstage URL
  BACKSTAGE_URL: "backstage-developer-hub-rhdh-operator.apps.cluster-wdw6r.wdw6r.gcp.redhatworkshops.io"


  # ARGOCD.
  ARGOCD_USERNAME: "admin"
  # TODO: set ARGOCD password
  # argocd password: oc get secret/openshift-gitops-cluster -n openshift-gitops -o jsonpath='{.data.admin\.password}' | base64 -d
  ARGOCD_PASSWORD: ***PUT YOUR PASSWORD***
  # TODO: set ARGOCD password
  # get argocd URL: oc get routes openshift-gitops-server -n openshift-gitops -o jsonpath='{.spec.host}'  
  ARGOCD_URL: "https://openshift-gitops-server-openshift-gitops.apps.cluster-wdw6r.wdw6r.gcp.redhatworkshops.io"

 # TODO: KEYCLOAK
  KEYCLOAK_REALM: "backstage" 
  KEYCLOAK_CLIENTID: "rhdh2vm"
  KEYCLOAK_CLIENTSECRET: ***PUT YOUR PASSWORD***
  KEYCLOAK_URL:  ***PUT YOUR KEYCLOAK URL***
  KEYCLOAK_URL_CATALOG: "https://apicurio-studio-auth.apps.ocp4.quitala.eu/auth"
  # TODO: Replace <rhdh_dns>
  KEYCLOAK_CALLBACK_URL: "https://[rhdh_dns]/api/auth/oidc/handler/frame"
 # TODO: KUBERNETES
  # oc -n rhdh-operator get secret rhdh-sa-token -o go-template='{{.data.token | base64decode}}'
  K8S_SERVICE_ACCOUNT_TOKEN: ***PUT YOUR PASSWORD***
  K8S_API_URL: "https://api.cluster-tp5x5.tp5x5.gcp.redhatworkshops.io:6443"
  
  # QUAY:
   
  QUAY_URL: quay.com/janus-backstage
  QUAY_CREDENTIALS: ***PUT YOUR PASSWORD***
  # GITHUB
  GITHUB_APPID: ***PUT YOUR PASSWORD***
  GITHUB_CLIENTID: ***PUT YOUR PASSWORD***
  GITHUB_CLIENTSECRET: ***PUT YOUR PASSWORD***
  GITHUB_PRIVATEKEY: ***PUT YOUR PASSWORD***
  
  
type: Opaque




