kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: backstage-k8s-plugin
subjects:
  - kind: ServiceAccount
    name: rhdh-operator
    namespace: rhdh-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: backstage-read-only
