kind: Secret
apiVersion: v1
metadata:
  name: rhdh2vm-argocd-cluster
  namespace: openshift-gitops-operator
  labels:
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/name: rhdh2vm-argocd-cluster
    app.kubernetes.io/part-of: argocd
data:
  admin.password: ***PUT YOUR PASSWORD***
type: Opaque