apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: keycloak
  namespace: keycloak
  annotations:
    olm.providedAPIs: Keycloak.v2alpha1.k8s.keycloak.org,KeycloakRealmImport.v2alpha1.k8s.keycloak.org  
spec:
  targetNamespaces: 
  - keycloak
  upgradeStrategy: Default