apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: my-realm-import
  namespace: keycloak
spec:
  keycloakCRName: example-keycloak
  realm:
    id: backstage
    realm: backstage
    enabled: true
    users:
      - username: user1
        enabled: true
        emailVerified: true
        email: user1@example.com
        credentials:
          - type: password
            value: user1
      - username: admin
        enabled: true
        emailVerified: true
        email: admin@example.com
        credentials:
          - type: password
            value: admin            
    roles:
      realm:
        - name: myrole
          description: A custom role
    clients:
      - clientId: backstage
        protocol: openid-connect
        enabled: true
        publicClient: false
        secret: my-predefined-client-secret
        redirectUris:
          - "https://backstage-developer-hub-rhdh-operator.apps.cluster-wdw6r.wdw6r.gcp.redhatworkshops.io/api/auth/oidc/handler/frame"
        webOrigins:
          - "https://backstage-developer-hub-rhdh-operator.apps.cluster-wdw6r.wdw6r.gcp.redhatworkshops.io"